### PR TITLE
Add PyLSL data format version.

### PR DESCRIPTION
**Pull request by gmierz**
This PR adds a version number to the channel meta data, see issue #6. I haven't had a chance to test it out with Pupil Capture yet.

### CODE REVIEW

**Comment by cboulay** [comment]
Please test it out, and record an xdf file using [LabRecorder](https://github.com/labstreaminglayer/App-LabRecorder/releases), then open the XDF file in [XDFBrowser](https://github.com/xdf-modules/XDFBrowser) (sorry it doesn't have a release page currently).

If the metadata looks OK in XDFBrowser then it should be fine.

**Comment by gmierz** [comment]
I keep seeing the following error when I try to run the XDFBrowser:
```
The thread 0x592c has exited with code -1073741701 (0xc000007b).
The thread 0x558c has exited with code -1073741701 (0xc000007b).
The thread 0x1ac has exited with code -1073741701 (0xc000007b).
The program '[5600] XDFBrowser.exe' has exited with code -1073741701 (0xc000007b).
```

Is it fine if I use `pyxdf` to open/load the XDF files and check the metadata from there?

**Comment by tstenner** [comment]
Could you upload the file somewhere?

**Comment by gmierz** [comment]
I've uploaded them to this link. In the archive, you'll find a test with the version, and one without the version: https://send.firefox.com/download/b7bc9ea1ad56c9d4/#DWZSHHK99Zmdz8Zt8Xds3g

The data is available for the next 7 days, or 50 downloads - I can upload it again after that if needed.

Also, can I use `pyxdf` to look at the data? I don't understand why XDFBrowser would need to be used here.

**Comment by tstenner** [comment]
Both files load just fine for me:

2019-09-08-124509_720x483_scrot-fs8

**Comment by tstenner** [comment]
Both files load just fine for me:

2019-09-08-124509_720x483_scrot-fs8

**Comment by cboulay** [comment]
The top-level xml info has a `version` item, and `desc` has a child `version` item. I know the child item is the one you made, but for a naive user, how do they know what each one is? Maybe you want to give your version a more descriptive tag like `data_format_version`, or hopefully something better than that?

There are a couple reasons I'd prefer you look at it in XDFBrowser. First, the C++ XML parser is likely to be stricter than what you get in Python and would be more likely to trigger an error. Second, XDFBrowser lays the header out in a nice table like this so you can look to see how your tag fits into the bigger picture.

**Comment by gmierz** [comment]
Ah ok I see thanks!

Good point, how does `pylsl_version` sound to you?

**Comment by cboulay** [comment]
Are you trying to keep track of the version of `pylsl` itself, or the version of the pupil-labs plugin data format?

**Comment by gmierz** [comment]
Oh right, the pupil-labs plugin - so `pupil_lsl_relay_version` would be better, what do you think?

**Comment by tstenner** [comment]
> There are a couple reasons I'd prefer you look at it in XDFBrowser. First, the C++ XML parser is likely to be stricter than what you get in Python and would be more likely to trigger an error.

The liblsl xml functions use the pugixml routines, so it should be impossible to get them to write invalid xml.

**Comment by gmierz** [comment]
Changed version name to `pupil_lsl_relay_version` to be more descriptive.

**Review by papr — APPROVED** [review]

**Pull request merged**
